version: "3"  

networks:
  tailscale_net:
    driver: bridge

  
services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    cap_add:
      - net_admin
      - sys_module
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    command: ["tailscaled"]
    privileged: true
    restart: unless-stopped
    networks:
      - tailscale_net
  llm_dash:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
      - "27017:27017"
    volumes:
      - .:/app
    networks:
      - tailscale_net
    depends_on:
      - tailscale

