# fly.toml app configuration file generated for llm-bench-back on 2023-10-26T20:11:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "llm-bench-back"
primary_region = "iad"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
